/**
 * zoom.mjs — the client-side half of the Zoom connector.
 *
 * Zoom Server-to-Server OAuth is NOT the browser-consent flow every other
 * connector in this repo uses. There is no redirect, no loopback listener and
 * no refresh token: the client creates an app in their own Zoom Marketplace
 * account and four values are displayed on two pages for them to copy. So this
 * module mirrors the POSTURE of `brain connect google` — print the steps for
 * the account YOU own, take credentials only through the environment, then
 * prove them live before claiming anything — and none of its OAuth mechanics.
 *
 * The verbs it exists to serve:
 *
 *   1. Tell the client exactly what to create, in their account, in the order
 *      that actually works.
 *   2. Probe the credentials against Zoom for real, so a wrong paste or a free
 *      plan is found here rather than after the first call they wanted read.
 *   3. Answer the bootstrap-ordering problem below.
 *
 * BOOTSTRAP ORDERING, the constraint that shapes the whole flow. Saving a
 * webhook URL in the Zoom Marketplace IS the validation request: Zoom POSTs an
 * `endpoint.url_validation` challenge to whatever URL was typed and refuses to
 * save an endpoint that answers it wrongly. So the worker must already be
 * deployed, already routing /api/webhooks/zoom, and already holding the Secret
 * Token BEFORE the client is told to paste the URL. Hence the step order in
 * `zoomEventSubscriptionSteps` is printed only after the secrets are written,
 * and `verifyLiveWebhookEndpoint` performs Zoom's exact handshake against the
 * live worker first — we hold the same Secret Token Zoom does, so this is not a
 * simulation of the check, it is the check.
 *
 * Nothing here is ours. The Zoom app, its four credentials, the recordings and
 * the worker they are written to all live in the client's own accounts.
 */

import {
  ZOOM_REQUIRED_SCOPE,
  ZOOM_RECORDING_EVENT,
  ZOOM_TRANSCRIPT_EVENT,
  describeZoomPlan,
  getZoomAccessToken,
  zoomHmacHex,
} from "../worker/src/lib/zoom.js";
import { ProviderSyncError, providerJson } from "./provider-sync.mjs";

/** The route the worker template serves. One place, so it cannot drift. */
export const ZOOM_WEBHOOK_PATH = "/api/webhooks/zoom";

/**
 * The four values copied out of the client's own Zoom app, and the four worker
 * secrets they become. Order is the order they appear in the Zoom UI, so the
 * error message reads like the page the client is looking at.
 *
 * All four are GENERATED BY ZOOM and copied. None is chosen here — in
 * particular the Secret Token is issued by Zoom on the app's Feature page and
 * cannot be set, which is why this module never offers to generate one.
 */
export const ZOOM_CREDENTIAL_ENV = Object.freeze([
  "ZOOM_ACCOUNT_ID",
  "ZOOM_CLIENT_ID",
  "ZOOM_CLIENT_SECRET",
  "ZOOM_WEBHOOK_SECRET_TOKEN",
]);

/**
 * Read-only, and OPTIONAL.
 *
 * Its single purpose is letting the connect step confirm the plan tier, which
 * is the difference between "this account cannot ever cloud record" and "this
 * could not be confirmed". It is offered rather than required because the
 * transcript path does not need it, and a connector that demands scopes it
 * never uses teaches clients to grant scopes without reading them.
 */
export const ZOOM_OPTIONAL_PLAN_SCOPE = "user:read:admin";

/** Zoom's own error code for "your app does not hold that scope". */
const ZOOM_SCOPE_ERROR_CODE = 4711;

/**
 * Where the webhook lives for a given install.
 *
 * Derived from the same manifest field the rest of the CLI resolves its base
 * URL from, so the URL the client pastes into Zoom is by construction the URL
 * their worker actually answers on.
 */
export function zoomWebhookUrl(base) {
  return `${String(base).replace(/\/+$/, "")}${ZOOM_WEBHOOK_PATH}`;
}

/**
 * Step one: what the client creates in their OWN Zoom account.
 *
 * Deliberately stops before the event subscription. That step cannot succeed
 * until the worker is holding the Secret Token, and printing it here would
 * invite the client to do it now and hit an opaque Zoom-side failure.
 */
export function zoomAppCreationSteps() {
  return [
    "In YOUR OWN Zoom account, signed in as an account owner or admin:",
    "",
    "  1. Go to marketplace.zoom.us, then Develop > Build App.",
    "  2. Choose Server-to-Server OAuth. Name it whatever you like.",
    "  3. On the App Credentials page, copy three values:",
    "       Account ID      -> ZOOM_ACCOUNT_ID",
    "       Client ID       -> ZOOM_CLIENT_ID",
    "       Client Secret   -> ZOOM_CLIENT_SECRET",
    "  4. On the Feature page, copy the Secret Token Zoom shows you:",
    "       Secret Token    -> ZOOM_WEBHOOK_SECRET_TOKEN",
    "     Zoom issues this one. You cannot choose it, and it is not the Client Secret.",
    `  5. On the Scopes page, add exactly one scope: ${ZOOM_REQUIRED_SCOPE}`,
    `     Optionally also add ${ZOOM_OPTIONAL_PLAN_SCOPE} (read-only). It is not needed to`,
    "     read transcripts; it only lets this step confirm your plan tier for you.",
    "  6. Activate the app. The credentials do not work until you do.",
    "",
    "  Supply all four values through your approved local launcher or secret",
    "  manager as environment variables. Never paste them into a shell command.",
    "  Then run this command again.",
  ];
}

/**
 * Step two, printed only once the worker is holding the Secret Token.
 *
 * This is the step that fails loudly if the ordering is wrong, which is exactly
 * why it is a separate function called later rather than more lines above.
 */
export function zoomEventSubscriptionSteps(webhookUrl) {
  return [
    "Back in your Zoom app, on the Feature page:",
    "",
    "  1. Turn on Event Subscriptions and add a subscription.",
    `  2. Event notification endpoint URL:  ${webhookUrl}`,
    "  3. Click Validate. Zoom calls that URL right now and refuses to save it",
    "     unless it answers correctly. Your brain is already holding the Secret",
    "     Token, and the answer was verified above, so this should pass.",
    "  4. Add exactly these two events:",
    `       ${ZOOM_RECORDING_EVENT}`,
    `       ${ZOOM_TRANSCRIPT_EVENT}`,
    "     The first records durable work debt as soon as the recording exists.",
    "     The second wakes that debt when the transcript is ready.",
    "  5. Save, then Activate the app again if Zoom asks.",
    "",
    "  Cloud recording with an audio transcript must also be on for the meetings",
    "  you want read (Zoom settings > Recording > Cloud recording > Audio",
    "  transcript). No recording means no transcript, and nothing to send.",
  ];
}

/**
 * Pull the four values from the environment, never from argv.
 *
 * Same custody rule as `brain connect google`: a credential on a command line
 * is a credential in shell history, in `ps` output, and in every terminal
 * scrollback it was ever printed to.
 */
export function readZoomCredentialsFromEnv(env = process.env) {
  const values = {};
  const missing = [];
  for (const name of ZOOM_CREDENTIAL_ENV) {
    const raw = env[name];
    if (typeof raw === "string" && raw.trim()) values[name] = raw.trim();
    else missing.push(name);
  }
  return { values, missing, complete: missing.length === 0 };
}

/**
 * Did Zoom refuse this because the app lacks the scope?
 *
 * Zoom answers a missing scope with HTTP 400 and code 4711 rather than a 403,
 * so a status check alone reads it as a malformed request and sends the client
 * looking in the wrong place.
 */
function isScopeRefusal(status, body) {
  if (status === 403) return true;
  return status === 400 && Number(body?.code) === ZOOM_SCOPE_ERROR_CODE;
}

async function readJsonQuietly(response) {
  try {
    return JSON.parse(await response.text());
  } catch {
    return null;
  }
}

/**
 * Prove the credentials against Zoom, live.
 *
 * Three findings, in the order that a failure is most likely and cheapest:
 *
 *   1. The token exchange. Proves the Account ID, Client ID, Client Secret and
 *      that the app is Activated. Everything else is unreachable without it.
 *   2. One cheap authenticated read of the recordings list. This is the exact
 *      permission the webhook path needs, so it proves the one required scope
 *      is actually granted rather than merely typed into the Scopes page.
 *   3. The plan tier. Attempted, never assumed. If the optional read-only user
 *      scope is not granted this returns `confirmed: false` and says so; a
 *      guess here would be the single most expensive kind of wrong, because a
 *      Basic account can never cloud record and so can never produce anything
 *      for this connector to read.
 *
 * Returns findings rather than printing or exiting, so the CLI decides what is
 * fatal and the tests can assert on the findings themselves.
 */
export async function probeZoomAccount(credentials, { fetchImpl = fetch, requestOptions = {} } = {}) {
  const token = await getZoomAccessToken({
    accountId: credentials.ZOOM_ACCOUNT_ID,
    clientId: credentials.ZOOM_CLIENT_ID,
    clientSecret: credentials.ZOOM_CLIENT_SECRET,
  }, { fetchImpl, requestOptions });

  const authed = async (path) => {
    try {
      const { data, response } = await providerJson(
        "zoom",
        `https://api.zoom.us/v2${path}`,
        { accessToken: token, fetchImpl, ...requestOptions },
      );
      return { ok: true, status: response.status, data, error: null };
    } catch (error) {
      if (!(error instanceof ProviderSyncError)) throw error;
      return {
        ok: false,
        status: error.status,
        data: null,
        error,
      };
    }
  };

  // The one call that proves the one required scope.
  const recordingsResponse = await authed("/users/me/recordings?page_size=1");
  const recordings = recordingsResponse.ok
    ? { ok: true, status: recordingsResponse.status, scopeMissing: false }
    : {
      ok: false,
      status: recordingsResponse.status,
      scopeMissing: isScopeRefusal(recordingsResponse.status, { code: recordingsResponse.error?.code }),
      message: String(recordingsResponse.error?.message || "").slice(0, 200) || null,
    };

  // The plan tier. Optional scope, so a refusal here is a named unknown and
  // never a failure of the connection itself.
  let plan = { confirmed: false, plan: describeZoomPlan(null), reason: null };
  try {
    const userResponse = await authed("/users/me");
    if (userResponse.ok) {
      const user = userResponse.data;
      plan = { confirmed: true, plan: describeZoomPlan(user?.type), reason: null };
    } else {
      plan = {
        confirmed: false,
        plan: describeZoomPlan(null),
        reason: isScopeRefusal(userResponse.status, { code: userResponse.error?.code })
          ? `the optional ${ZOOM_OPTIONAL_PLAN_SCOPE} scope is not granted, so the plan tier could not be read`
          : userResponse.error?.outcome?.kind === "retryable"
            ? String(userResponse.error.message || "Zoom could not be reached").slice(0, 160)
            : `Zoom would not report the plan tier (HTTP ${userResponse.status})`,
      };
    }
  } catch (error) {
    plan = {
      confirmed: false,
      plan: describeZoomPlan(null),
      reason: `the plan-tier check could not run: ${String(error?.message || error).slice(0, 160)}`,
    };
  }

  return { token, recordings, plan };
}

/**
 * Turn a probe into a decision.
 *
 * `blockers` stop the connect outright; `notes` are things the client should
 * know but that do not make the connection a lie. The split matters: a Basic
 * plan is a blocker because the connector provably cannot ever work on it, but
 * an unconfirmed plan is only a note, because refusing there would strand every
 * client who reasonably declined the optional scope.
 */
export function summarizeZoomProbe(probe) {
  const blockers = [];
  const notes = [];

  if (!probe.recordings.ok) {
    blockers.push(
      probe.recordings.scopeMissing
        ? `the Zoom app does not hold the ${ZOOM_REQUIRED_SCOPE} scope. Add it on the app's Scopes page, activate the app again, then rerun.`
        : `Zoom refused the recordings read (HTTP ${probe.recordings.status})${probe.recordings.message ? `: ${probe.recordings.message}` : ""}`,
    );
  }

  if (probe.plan.confirmed && probe.plan.plan.cloudRecording === false) {
    blockers.push(
      `this Zoom account is on the ${probe.plan.plan.label} plan. ${probe.plan.plan.detail} ` +
      "Nothing was written; upgrade the seat and rerun.",
    );
  } else if (probe.plan.confirmed) {
    notes.push(`Zoom plan: ${probe.plan.plan.label}. Cloud recording is available on this account.`);
  } else {
    notes.push(
      `Zoom plan: not confirmed — ${probe.plan.reason || "the plan tier could not be read"}. ` +
      "Cloud recording requires a Licensed (paid) seat; a Basic account cannot produce transcripts at all. " +
      "Check yours at zoom.us/profile before relying on this.",
    );
  }

  return { ok: blockers.length === 0, blockers, notes };
}

/**
 * Run Zoom's own URL-validation handshake against the live worker.
 *
 * Not a simulation. We hold the same Secret Token Zoom does, so this sends the
 * identical challenge body Zoom sends and checks the identical HMAC answer Zoom
 * checks. If this passes, the client's paste into the Marketplace will pass;
 * if it fails, we can say WHICH part is wrong instead of leaving them with
 * Zoom's opaque "URL validation failed".
 *
 * The plainToken is random per call so a worker that echoed a cached answer,
 * or answered without consulting the secret at all, cannot pass this.
 */
export async function verifyLiveWebhookEndpoint(webhookUrl, secretToken, {
  fetchImpl = fetch,
  plainToken = randomPlainToken(),
} = {}) {
  const expected = await zoomHmacHex(secretToken, plainToken);
  let response;
  try {
    response = await fetchImpl(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        event: "endpoint.url_validation",
        payload: { plainToken },
        event_ts: Date.now(),
      }),
    });
  } catch (error) {
    return {
      ok: false,
      reason: `the brain did not answer at ${webhookUrl}: ${String(error?.message || error).slice(0, 160)}`,
    };
  }

  if (response.status === 503) {
    return {
      ok: false,
      reason: "the brain answered, but reports the Zoom webhook is not configured. The worker is running an older build, or the secret did not stick. Redeploy with `brain deploy <manifest>` and rerun.",
    };
  }
  if (!response.ok) {
    return { ok: false, reason: `the brain answered ${response.status} at ${webhookUrl}, not the validation challenge. Check that this URL is the brain and that it is deployed.` };
  }

  const body = await readJsonQuietly(response);
  if (!body || typeof body.encryptedToken !== "string" || body.plainToken !== plainToken) {
    return { ok: false, reason: "the brain answered, but not with Zoom's challenge shape. It is almost certainly running a build from before this connector existed; redeploy it." };
  }
  if (body.encryptedToken !== expected) {
    return {
      ok: false,
      reason: "the brain answered the challenge with a different signature, which means the Secret Token it holds is not the one supplied here. Rerun this command so the secret is rewritten, or recheck the Secret Token on the Zoom app's Feature page.",
    };
  }
  return { ok: true, reason: null };
}

/** A fresh challenge value, so no answer can be replayed or cached into a pass. */
export function randomPlainToken() {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}
